services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olaclick-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: sh -c "php artisan migrate --force || true && php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - ./:/var/www/html

  db:
    image: postgres:16-alpine
    container_name: olaclick-db
    environment:
      POSTGRES_DB: olaclick
      POSTGRES_USER: olaclick
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: olaclick-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
